"""Issue #32: Vorgang.kurztitel is a short, human-readable title (DD-053).

Agreed requirement (https://github.com/Parlamentszusammenfasser/pazufa-scraper-bw/issues/32):

1. Always generated by the LLM from ``titel`` + the initiating document's
   ``zusammenfassung``; at most 60 characters. A title that is already short and
   informative may come back unchanged.
2. Single line, no slug; trailing period / quotes are stripped. A rule
   violation is re-prompted once.
3. Fallback (LLM off, error, still invalid after the retry): ``kurztitel = titel``.
   Never ``None``, never a URL slug.
4. Cached per (titel, summary, prompt) so it stays stable between runs.
"""

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from bawue.bawue_dok import KURZTITEL_MAX_LEN, vorgang_kurztitel

LONG_TITEL = (
    "Gesetz zum besseren Schutz vor Straftaten gegen die sexuelle Selbstbestimmung "
    "und Gefahren aufgrund häuslicher Gewalt"
)
SUMMARY = "Der Entwurf verbessert den Schutz von Opfern häuslicher Gewalt."
GOOD = "Besserer Schutz vor Sexualstraftaten und häuslicher Gewalt"


def _llm():
    llm = MagicMock()
    llm.api_key = "test-key"
    llm.temperature = 0.1
    llm.timeout_seconds = 60.0
    return llm


def _response(kurztitel: str):
    resp = MagicMock()
    resp.choices = [MagicMock()]
    resp.choices[0].message.content = json.dumps({"kurztitel": kurztitel}, ensure_ascii=False)
    return resp


def _patch_llm(*kurztitel: str):
    """Patch litellm so consecutive calls return the given kurztitel values."""
    return patch(
        "bawue.bawue_dok.litellm.acompletion",
        new_callable=AsyncMock,
        side_effect=[_response(k) for k in kurztitel],
    )


def _empty_cache():
    cache = MagicMock()
    cache.get_raw.return_value = None
    return cache


class TestVorgangKurztitel:
    @pytest.mark.asyncio
    async def test_llm_disabled_falls_back_to_titel(self):
        assert await vorgang_kurztitel(None, LONG_TITEL, SUMMARY) == LONG_TITEL

    @pytest.mark.asyncio
    async def test_generates_short_title_from_titel_and_summary(self):
        with _patch_llm(GOOD) as acomp:
            result = await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY, cache=_empty_cache())

        assert result == GOOD
        prompt = acomp.call_args.kwargs["messages"][-1]["content"]
        assert LONG_TITEL in prompt
        assert SUMMARY in prompt

    @pytest.mark.asyncio
    async def test_short_titel_may_come_back_unchanged(self):
        with _patch_llm("Effizienzgesetz"):
            assert await vorgang_kurztitel(_llm(), "Effizienzgesetz", SUMMARY) == "Effizienzgesetz"

    @pytest.mark.asyncio
    async def test_too_long_output_is_reprompted_once(self):
        too_long = "x" * (KURZTITEL_MAX_LEN + 1)
        with _patch_llm(too_long, GOOD) as acomp:
            result = await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY)

        assert result == GOOD
        assert acomp.call_count == 2
        # The retry tells the model what was wrong with its first answer.
        retry_messages = acomp.call_args_list[1].kwargs["messages"]
        assert too_long in retry_messages[-2]["content"]
        assert str(KURZTITEL_MAX_LEN) in retry_messages[-1]["content"]

    @pytest.mark.asyncio
    async def test_still_invalid_after_retry_falls_back_to_titel(self):
        too_long = "x" * (KURZTITEL_MAX_LEN + 1)
        with _patch_llm(too_long, too_long) as acomp:
            result = await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY)

        assert result == LONG_TITEL
        assert acomp.call_count == 2

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "bad",
        [
            "dienst-und-versorgungsbezuege",  # URL slug — the original #32 symptom
            "Schutz vor Gewalt\nund Straftaten",  # multi-line
            "",
        ],
    )
    async def test_rule_violations_are_rejected(self, bad):
        with _patch_llm(bad, bad):
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == LONG_TITEL

    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "bad",
        [
            "Gesetz zur Änderung des Abgeordnetengesetzes",  # acceptance example: boilerplate echoed
            "Entwurf eines Gesetzes zur Änderung des Schulgesetzes",
            "Änderung von § 5 Landeswahlgesetz",
            "Neufassung von Artikel 3 der Verfassung",
        ],
    )
    async def test_legal_boilerplate_is_reprompted(self, bad):
        """Rule 2: legal boilerplate / article references get the agreed re-prompt."""
        with _patch_llm(bad, GOOD) as acomp:
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == GOOD
        assert acomp.call_count == 2

    @pytest.mark.asyncio
    async def test_abbreviation_period_is_kept(self):
        with _patch_llm("Förderung für Sportvereine e.V."):
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == "Förderung für Sportvereine e.V."

    @pytest.mark.asyncio
    async def test_trailing_period_and_quotes_are_stripped(self):
        with _patch_llm(f"„{GOOD}.“"):
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == GOOD

    @pytest.mark.asyncio
    async def test_angle_brackets_are_sanitized(self):
        """DD-027: the backend's XSS validator rejects < and >."""
        with _patch_llm("Schutz vor Gewalt</narrow>"):
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == "Schutz vor Gewalt"

    @pytest.mark.asyncio
    async def test_llm_error_falls_back_to_titel(self):
        with patch("bawue.bawue_dok.litellm.acompletion", new_callable=AsyncMock, side_effect=RuntimeError("down")):
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY) == LONG_TITEL

    @pytest.mark.asyncio
    async def test_result_is_cached_in_redis(self):
        cache = _empty_cache()
        with _patch_llm(GOOD):
            await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY, cache=cache)

        key, value = cache.store_raw.call_args[0][:2]
        assert key.startswith("vorgang-kurztitel:")
        assert value == GOOD

    @pytest.mark.asyncio
    async def test_cache_hit_skips_llm(self):
        cache = MagicMock()
        cache.get_raw.return_value = GOOD
        with _patch_llm() as acomp:
            assert await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY, cache=cache) == GOOD
        acomp.assert_not_called()

    @pytest.mark.asyncio
    async def test_cache_key_depends_on_summary(self):
        keys = []
        for summary in ("A", "B"):
            cache = _empty_cache()
            with _patch_llm(GOOD):
                await vorgang_kurztitel(_llm(), LONG_TITEL, summary, cache=cache)
            keys.append(cache.store_raw.call_args[0][0])
        assert keys[0] != keys[1]

    @pytest.mark.asyncio
    async def test_fallback_is_not_cached(self):
        """A transient LLM failure must not pin the long titel for future runs."""
        cache = _empty_cache()
        with patch("bawue.bawue_dok.litellm.acompletion", new_callable=AsyncMock, side_effect=RuntimeError("down")):
            await vorgang_kurztitel(_llm(), LONG_TITEL, SUMMARY, cache=cache)
        cache.store_raw.assert_not_called()
